version: '2'
services:


  database:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGODB_USER="astrologer" 
      - MONGODB_PASS="owanesh_stagi_horoscofox"
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: -smallfiles -nojournal
    
  backend:
    container_name: apistar
    build: ./horoscofox-service
    depends_on:
      - database
    links:
      - database
    ports:
      - 9001:9001
    environment: 
      PYTHONUNBUFFERED: 0
    command: ['/app/horoscofox-service/utils/pre-deploy-commands.sh']
    volumes:
      - ./horoscofox-service:/app/horoscofox-service
