version: '2'
services:

  postgres:
    container_name: horoscofox_database
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: horoscofoxuser
      POSTGRES_DB: horoscofox
      POSTGRES_PASSWORD: horoscopsw
    ports:
     - "5432:5432"
   

  backend:
    container_name: horoscofox_server
    build: ./horoscofox-service
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 9001:9001
    environment: 
      SECRET_KEY: 123 
      DEBUG: 'True' 
      PYTHONUNBUFFERED: 0
    entrypoint: ["/app/horoscofox-service/utils/entrypoint-wait-for-postgres.sh", "postgres", "--"]
    command: ['/app/horoscofox-service/utils/pre-deploy-commands.sh']
    volumes:
      - ./horoscofox-service:/app/horoscofox-service
