# Generated by Django 2.0.3 on 2018-04-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_start', models.DateField(null=True)),
                ('date_end', models.DateField(null=True)),
                ('sign', models.IntegerField(choices=[(0, 'capricorn'), (1, 'acquarius'), (2, 'pisces'), (3, 'aries'), (4, 'taurus'), (5, 'gemini'), (6, 'cancer'), (7, 'leo'), (8, 'virgo'), (9, 'libra'), (10, 'scorpio'), (11, 'sagittarius')], default=1)),
                ('kind', models.IntegerField(choices=[(1, 'today'), (2, 'tomorrow'), (3, 'month'), (4, 'info')], default=1)),
            ],
        ),
    ]
